//! Deterministic remediation prompt for pasting into an LLM or editor agent.
//! Zerum does not call an LLM; it only assembles findings + optional snippets.

use crate::core::{Issue, Severity};
use crate::reporters::Reporter;
use anyhow::Result;
use std::cmp::Reverse;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

pub struct RemediationPromptReporter {
    /// Root path that was checked (for prompt context).
    pub checked_path: String,
    /// Lines of source context around each finding (before and after).
    pub context_lines: usize,
}

impl Default for RemediationPromptReporter {
    fn default() -> Self {
        Self {
            checked_path: ".".into(),
            context_lines: 8,
        }
    }
}

impl Reporter for RemediationPromptReporter {
    fn report(&self, issues: &[Issue]) -> Result<String> {
        render_prompt(issues, &self.checked_path, self.context_lines)
    }
}

fn group_key(issue: &Issue) -> (String, String) {
    (issue.id.clone(), issue.title.clone())
}

/// Group by check id/title; groups and occurrences ordered by severity (highest first).
fn grouped_findings(issues: &[Issue]) -> Vec<(String, String, Severity, Vec<&Issue>)> {
    let mut map: BTreeMap<(String, String), Vec<&Issue>> = BTreeMap::new();
    for issue in issues {
        map.entry(group_key(issue)).or_default().push(issue);
    }

    let mut groups: Vec<(String, String, Severity, Vec<&Issue>)> = map
        .into_iter()
        .map(|((id, title), mut items)| {
            items.sort_by(|a, b| {
                Reverse(a.severity)
                    .cmp(&Reverse(b.severity))
                    .then_with(|| a.file.cmp(&b.file))
                    .then_with(|| a.line.cmp(&b.line))
                    .then_with(|| a.column.cmp(&b.column))
                    .then_with(|| a.message.cmp(&b.message))
            });
            let max_sev = items
                .iter()
                .map(|i| i.severity)
                .max()
                .unwrap_or(Severity::Info);
            (id, title, max_sev, items)
        })
        .collect();

    groups.sort_by(|a, b| Reverse(a.2).cmp(&Reverse(b.2)).then_with(|| a.0.cmp(&b.0)));
    groups
}

pub fn render_prompt(issues: &[Issue], checked_path: &str, context_lines: usize) -> Result<String> {
    let mut out = String::new();
    writeln!(
        out,
        "# Zerum remediation prompt\n\
         \n\
         You are fixing Python code quality issues reported by **Zerum**, a\n\
         deterministic static analyzer (not a linter clone of Ruff).\n\
         \n\
         ## Goal\n\
         Apply the remediations below with **minimal, correct** edits. Do not\n\
         invent unrelated refactors, renames, or style changes beyond what each\n\
         finding asks for. Preserve public APIs unless a finding requires changing them.\n\
         \n\
         Work **by type** (highest severity groups first). Within each type, fix\n\
         occurrences in the listed order.\n\
         \n\
         When done, the checked tree should pass:\n\
         ```bash\n\
         zerum check {checked_path}\n\
         ```\n"
    )?;

    if issues.is_empty() {
        writeln!(
            out,
            "## Summary\n\nNo issues found. Nothing to remediate.\n"
        )?;
        return Ok(out);
    }

    let groups = grouped_findings(issues);
    let mut by_file: BTreeMap<&Path, usize> = BTreeMap::new();
    for issue in issues {
        *by_file.entry(issue.file.as_path()).or_insert(0) += 1;
    }

    writeln!(
        out,
        "## Summary\n\
         \n\
         - Checked path: `{checked_path}`\n\
         - Findings: **{}** across **{}** file(s), **{}** type(s)\n\
         - Ordered by severity (critical → info), then grouped by check id\n\
         - Generated by Zerum (deterministic; no model was invoked)\n",
        issues.len(),
        by_file.len(),
        groups.len()
    )?;

    writeln!(out, "### Types (severity order)\n")?;
    for (id, title, sev, items) in &groups {
        writeln!(
            out,
            "- `{id}` — {title} — **{sev}** — {} occurrence(s)",
            items.len()
        )?;
    }
    writeln!(out)?;

    writeln!(out, "## Findings by type\n")?;

    for (group_idx, (id, title, group_sev, items)) in groups.iter().enumerate() {
        let g = group_idx + 1;
        writeln!(
            out,
            "## {g}. `{id}` — {title}\n\
             \n\
             - **Group severity:** {group_sev} (highest among occurrences)\n\
             - **Occurrences:** {}\n\
             - **Category:** {}\n",
            items.len(),
            items[0].category,
        )?;

        if let Some(explanation) = &items[0].explanation {
            writeln!(out, "- **Explanation:** {explanation}\n")?;
        }
        if let Some(remediation) = &items[0].remediation {
            writeln!(out, "- **Shared remediation:** {remediation}\n")?;
        }

        for (occ_idx, issue) in items.iter().enumerate() {
            let n = occ_idx + 1;
            writeln!(
                out,
                "### {g}.{n} `{file}:{line}:{column}` [{severity}]\n\
                 \n\
                 - **Message:** {message}\n",
                file = issue.file.display(),
                line = issue.line,
                column = issue.column,
                severity = issue.severity,
                message = issue.message,
            )?;
            if let Some(snippet) = source_snippet(&issue.file, issue.line, context_lines) {
                writeln!(out, "Source context:\n\n```python\n{snippet}```\n")?;
            }
        }
    }

    writeln!(
        out,
        "## Instructions for the assistant\n\
         \n\
         1. Fix groups in order (highest severity types first).\n\
         2. Within a type, apply the **Shared remediation** to each occurrence.\n\
         3. Prefer the smallest change that addresses the finding.\n\
         4. Do not silence findings by deleting useful code or weakening error handling\n\
            unless the remediation explicitly allows it.\n\
         5. After edits, re-run `zerum check {checked_path}` and resolve any remaining issues.\n"
    )?;

    Ok(out)
}

fn source_snippet(path: &Path, line: usize, context_lines: usize) -> Option<String> {
    let content = fs::read_to_string(path).ok()?;
    let lines: Vec<&str> = content.lines().collect();
    if lines.is_empty() || line == 0 {
        return None;
    }
    let idx = line.saturating_sub(1);
    if idx >= lines.len() {
        return None;
    }
    let start = idx.saturating_sub(context_lines);
    let end = (idx + context_lines + 1).min(lines.len());
    let mut buf = String::new();
    for (i, text) in lines[start..end].iter().enumerate() {
        let lineno = start + i + 1;
        let marker = if lineno == line { ">" } else { " " };
        let _ = writeln!(buf, "{marker}{lineno:>5}| {text}");
    }
    Some(buf)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{Category, ConfidenceKind};
    use std::borrow::Cow;
    use std::path::PathBuf;

    fn issue(
        id: &str,
        title: &str,
        severity: Severity,
        file: &str,
        line: usize,
        message: &str,
    ) -> Issue {
        Issue {
            id: id.into(),
            title: title.into(),
            message: message.into(),
            explanation: Some(Cow::Borrowed("why")),
            remediation: Some(Cow::Borrowed("fix it")),
            file: PathBuf::from(file),
            line,
            column: 1,
            severity,
            category: Category::Readability,
            source: "zerum".into(),
            confidence: ConfidenceKind::Deterministic,
        }
    }

    #[test]
    fn empty_issues_prompt() {
        let out = render_prompt(&[], "src", 2).unwrap();
        assert!(out.contains("No issues found"));
        assert!(out.contains("zerum check src"));
    }

    #[test]
    fn prompt_includes_finding_and_snippet() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("mod.py");
        fs::write(&path, "def f():\n    return 1\n    return 2\n").unwrap();
        let issue = issue(
            "ZR001",
            "long-function",
            Severity::Low,
            path.to_str().unwrap(),
            2,
            "too long",
        );
        let out = render_prompt(&[issue], ".", 1).unwrap();
        assert!(out.contains("ZR001"));
        assert!(out.contains("fix it"));
        assert!(out.contains("```python"));
        assert!(out.contains(">    2|"));
        assert!(out.contains("Findings by type"));
    }

    #[test]
    fn groups_by_type_and_orders_by_severity() {
        let issues = vec![
            issue("ZR006", "magic-number", Severity::Low, "a.py", 10, "3"),
            issue("ZR401", "broad-except", Severity::High, "b.py", 2, "except"),
            issue("ZR006", "magic-number", Severity::Low, "a.py", 3, "4"),
            issue(
                "ZR001",
                "long-function",
                Severity::Medium,
                "c.py",
                1,
                "long",
            ),
            issue(
                "ZR401",
                "broad-except",
                Severity::Critical,
                "b.py",
                20,
                "base",
            ),
        ];
        let out = render_prompt(&issues, ".", 0).unwrap();

        let types = out.find("### Types (severity order)").unwrap();
        let findings = out.find("## Findings by type").unwrap();
        let toc = &out[types..findings];
        let i401 = toc.find("`ZR401`").unwrap();
        let i001 = toc.find("`ZR001`").unwrap();
        let i006 = toc.find("`ZR006`").unwrap();
        assert!(i401 < i001 && i001 < i006, "toc severity order: {toc}");

        let g401 = out.find("## 1. `ZR401`").unwrap();
        let g001 = out.find("## 2. `ZR001`").unwrap();
        let g006 = out.find("## 3. `ZR006`").unwrap();
        assert!(g401 < g001 && g001 < g006);

        // Within ZR401, critical occurrence before high
        let zr401_section = &out[g401..g001];
        let crit = zr401_section.find("[critical]").unwrap();
        let high = zr401_section.find("[high]").unwrap();
        assert!(crit < high, "within-type severity order");

        // Shared remediation once per group
        assert_eq!(out.matches("**Shared remediation:**").count(), 3);
    }
}
