use crate::core::{Category, Check, CheckContext, Issue, Severity};

const PATTERNS: &[&str] = &[
    "TODO: AI",
    "FIXME: AI",
    "GENERATED BY AI",
    "CHATGPT",
    "COPILOT",
    "AUTO-GENERATED",
];

pub struct AiPlaceholderComment;

impl Check for AiPlaceholderComment {
    fn id(&self) -> &'static str {
        "ZR009"
    }

    fn name(&self) -> &'static str {
        "ai-generated-placeholder-comment"
    }

    fn category(&self) -> Category {
        Category::Ai
    }

    fn severity(&self) -> Severity {
        Severity::Medium
    }

    fn explanation(&self) -> &'static str {
        "Placeholder comments often indicate incomplete AI-assisted edits that were not finished or reviewed."
    }

    fn remediation(&self) -> &'static str {
        "Replace placeholders with real implementation, tests, and documentation; remove marketing boilerplate."
    }

    fn run(&self, ctx: &CheckContext) -> Vec<Issue> {
        if !ctx.config.is_check_enabled(self.id()) {
            return Vec::new();
        }

        ctx.source
            .lines()
            .enumerate()
            .filter_map(|(idx, line)| {
                let upper = line.to_uppercase();
                PATTERNS
                    .iter()
                    .find(|p| upper.contains(&p.to_uppercase()))
                    .map(|pattern| {
                        let column = line
                            .to_uppercase()
                            .find(&pattern.to_uppercase())
                            .map(|i| i + 1)
                            .unwrap_or(1);
                        Issue::deterministic(
                            self.id(),
                            self.name(),
                            format!("suspicious AI-related placeholder: `{pattern}`"),
                            ctx.file_path(),
                            idx + 1,
                            column,
                            self.severity(),
                            self.category(),
                        )
                        .with_guidance(self.explanation(), self.remediation())
                    })
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Config;
    use crate::parser::{PythonParser, RustPythonParser};
    use std::path::Path;

    #[test]
    fn detects_ai_placeholder() {
        let source = "# TODO: AI fill in implementation\npass\n";
        let parser = RustPythonParser;
        let path = Path::new("x.py");
        let parsed = parser.parse_file(source, path).unwrap();
        let config = Config::default();
        let ctx = CheckContext {
            path,
            source,
            parsed: &parsed,
            config: &config,
        };
        let issues = AiPlaceholderComment.run(&ctx);
        assert_eq!(issues.len(), 1);
        assert_eq!(issues[0].id, "ZR009");
    }
}
