//! AST-precise detector implementations used by the rule catalog.

use crate::core::ast_util::{
    is_broad_except_handler, is_mutable_expr, walk_exprs_in_module, walk_module_level_stmts,
    walk_stmts_for_try, walk_stmts_in_module,
};
use crate::core::{Check, CheckContext, Issue};
use crate::parser::line_col;
use rustpython_ast::{Constant, ExceptHandler, Expr, Stmt, Ranged};

pub fn run_detector(check: &dyn Check, ctx: &CheckContext, detector: CatalogDetector) -> Vec<Issue> {
    if !ctx.config.is_check_enabled(check.id()) {
        return Vec::new();
    }
    match detector {
        CatalogDetector::CommentedOutCode => detect_commented_out_code(check, ctx),
        CatalogDetector::AiPlaceholderInComment => detect_ai_placeholder_in_comment(check, ctx),
        CatalogDetector::GeneratedCommentPattern => detect_generated_comment_pattern(check, ctx),
        CatalogDetector::GeneratedDeadBranch => detect_generated_dead_branch(check, ctx),
        CatalogDetector::RedundantBooleanComparison => detect_redundant_boolean_comparison(check, ctx),
        CatalogDetector::DataclassWithoutBehavior => detect_dataclass_without_behavior(check, ctx),
        CatalogDetector::GlobalMutableAssignment => detect_global_mutable_assignment(check, ctx),
        CatalogDetector::ExceptHandlerOnlyPass { bare_only } => {
            detect_except_handler_only_pass(check, ctx, bare_only)
        }
        CatalogDetector::MixedStringQuotes => detect_mixed_string_quotes(check, ctx),
        CatalogDetector::ShortVariableName => detect_short_variable_names(check, ctx),
        CatalogDetector::TestAndShouldFunctionMix => detect_test_and_should_mix(check, ctx),
        CatalogDetector::DefensiveNamingSuffix => detect_defensive_naming_suffix(check, ctx),
        CatalogDetector::ServiceNamingExplosion => detect_service_naming_explosion(check, ctx),
        CatalogDetector::UnnecessaryElseAfterReturn => detect_unnecessary_else_after_return(check, ctx),
        CatalogDetector::IdentityPassthrough => detect_identity_passthrough(check, ctx),
        CatalogDetector::IdentityMap => detect_identity_map(check, ctx),
        CatalogDetector::BlanketExceptException => detect_blanket_except_exception(check, ctx),
        CatalogDetector::SilentFallbackReturnNone => detect_silent_fallback_return_none(check, ctx),
        CatalogDetector::GenericExceptionMessage => detect_generic_exception_message(check, ctx),
    }
}

#[derive(Debug, Clone, Copy)]
pub enum CatalogDetector {
    CommentedOutCode,
    AiPlaceholderInComment,
    GeneratedCommentPattern,
    GeneratedDeadBranch,
    RedundantBooleanComparison,
    DataclassWithoutBehavior,
    GlobalMutableAssignment,
    ExceptHandlerOnlyPass { bare_only: bool },
    MixedStringQuotes,
    ShortVariableName,
    TestAndShouldFunctionMix,
    DefensiveNamingSuffix,
    ServiceNamingExplosion,
    UnnecessaryElseAfterReturn,
    IdentityPassthrough,
    IdentityMap,
    BlanketExceptException,
    SilentFallbackReturnNone,
    GenericExceptionMessage,
}

fn detect_commented_out_code(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let markers = ["def ", "class ", "return ", "import ", "raise "];
    let mut issues = Vec::new();
    for comment in ctx.source_model().comments() {
        let body = comment.text.trim_start_matches('#').trim();
        let lower = body.to_ascii_lowercase();
        if markers.iter().any(|m| lower.starts_with(m)) {
            issues.push(Issue::from_check(
                check,
                "comment appears to contain commented-out executable code",
                ctx.file_path(),
                comment.line,
                comment.column,
            ));
        }
    }
    issues
}

fn detect_ai_placeholder_in_comment(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let needles = ["TODO: AI", "FIXME: AI", "GENERATED BY AI"];
    let mut issues = Vec::new();
    for comment in ctx.source_model().comments() {
        let upper = comment.text.to_ascii_uppercase();
        if needles.iter().any(|n| upper.contains(n)) {
            issues.push(Issue::from_check(
                check,
                "AI placeholder marker found in comment",
                ctx.file_path(),
                comment.line,
                comment.column,
            ));
        }
    }
    issues
}

fn detect_generated_comment_pattern(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let needles = ["GENERATED BY", "AUTO-GENERATED"];
    let mut issues = Vec::new();
    for comment in ctx.source_model().comments() {
        let upper = comment.text.to_ascii_uppercase();
        if needles.iter().any(|n| upper.contains(n)) {
            issues.push(Issue::from_check(
                check,
                "generated-code marker in comment",
                ctx.file_path(),
                comment.line,
                comment.column,
            ));
        }
    }
    issues
}

fn detect_generated_dead_branch(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::If(i) = stmt {
            if is_constant_bool(&i.test, true) || is_constant_bool(&i.test, false) {
                let (line, col) = line_col(&ctx.parsed.source, i.start().into());
                issues.push(Issue::from_check(
                    check,
                    "constant boolean condition suggests generated or placeholder branch",
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_redundant_boolean_comparison(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_exprs_in_module(ctx.parsed, &mut |expr| {
        if let Expr::Compare(c) = expr {
            if compare_uses_bool_constant(&c.left, true)
                || compare_uses_bool_constant(&c.left, false)
                || c.comparators.iter().any(|e| {
                    compare_uses_bool_constant(e, true) || compare_uses_bool_constant(e, false)
                })
            {
                let (line, col) = line_col(&ctx.parsed.source, expr.start().into());
                issues.push(Issue::from_check(
                    check,
                    "redundant comparison to True/False constant",
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_dataclass_without_behavior(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::ClassDef(c) = stmt {
            if !has_dataclass_decorator(c) {
                return;
            }
            let only_pass = !c.body.is_empty() && c.body.iter().all(|s| matches!(s, Stmt::Pass(_)));
            if only_pass {
                let (line, col) = line_col(&ctx.parsed.source, c.start().into());
                issues.push(Issue::from_check(
                    check,
                    format!("dataclass `{}` has no behavior beyond pass", c.name),
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_global_mutable_assignment(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_module_level_stmts(ctx.parsed, &mut |stmt| {
        if let Stmt::Assign(a) = stmt {
            if is_mutable_expr(&a.value) {
                let (line, col) = line_col(&ctx.parsed.source, a.start().into());
                issues.push(Issue::from_check(
                    check,
                    "module-level assignment to mutable literal",
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_except_handler_only_pass(
    check: &dyn Check,
    ctx: &CheckContext,
    bare_only: bool,
) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_for_try(ctx.parsed, &mut |handler| {
        let ExceptHandler::ExceptHandler(h) = handler;
        if bare_only && h.type_.is_some() {
            return;
        }
        if !bare_only && h.type_.is_none() {
            return;
        }
        if is_only_pass_stmts(&h.body) {
            let (line, col) = line_col(&ctx.parsed.source, h.start().into());
            let msg = if h.type_.is_none() {
                "bare except handler only contains pass"
            } else if is_broad_except_handler(handler) {
                "broad except handler only contains pass"
            } else {
                "except handler only contains pass"
            };
            issues.push(Issue::from_check(check, msg, ctx.file_path(), line, col));
        }
    });
    issues
}

fn detect_mixed_string_quotes(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut single = false;
    let mut double = false;
    walk_exprs_in_module(ctx.parsed, &mut |expr| {
        if let Expr::Constant(c) = expr {
            if matches!(c.value, Constant::Str(_)) {
                let start: usize = expr.start().into();
                let end: usize = expr.end().into();
                if start < end && end <= ctx.parsed.source.len() {
                    let slice = &ctx.parsed.source[start..end];
                    if slice.starts_with('\'') {
                        single = true;
                    }
                    if slice.starts_with('"') {
                        double = true;
                    }
                }
            }
        }
    });
    if single && double {
        vec![Issue::from_check(
            check,
            "module mixes single- and double-quoted string literals",
            ctx.file_path(),
            1,
            1,
        )]
    } else {
        Vec::new()
    }
}

fn detect_short_variable_names(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::Assign(a) = stmt {
            for target in &a.targets {
                if let Expr::Name(n) = target {
                    if n.id.as_str().len() <= 2 {
                        let (line, col) = line_col(&ctx.parsed.source, a.start().into());
                        issues.push(Issue::from_check(
                            check,
                            format!("very short variable name `{}`", n.id),
                            ctx.file_path(),
                            line,
                            col,
                        ));
                    }
                }
            }
        }
    });
    issues
}

fn detect_test_and_should_mix(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut test_style = false;
    let mut should_style = false;
    for f in ctx.source_model().functions() {
        if f.name.starts_with("test_") {
            test_style = true;
        }
        if f.name.starts_with("should_") {
            should_style = true;
        }
    }
    if test_style && should_style {
        vec![Issue::from_check(
            check,
            "module mixes test_* and should_* function naming styles",
            ctx.file_path(),
            1,
            1,
        )]
    } else {
        Vec::new()
    }
}

fn detect_defensive_naming_suffix(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let suffixes = ["Factory", "Builder", "Strategy"];
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::ClassDef(c) = stmt {
            for s in suffixes {
                if c.name.as_str().ends_with(s) {
                    let (line, col) = line_col(&ctx.parsed.source, c.start().into());
                    issues.push(Issue::from_check(
                        check,
                        format!("class `{}` uses defensive suffix `{s}`", c.name),
                        ctx.file_path(),
                        line,
                        col,
                    ));
                }
            }
        }
    });
    issues
}

fn detect_service_naming_explosion(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let suffixes = ["Service", "Manager", "Handler"];
    let count = ctx
        .source_model()
        .classes()
        .into_iter()
        .filter(|c| suffixes.iter().any(|s| c.name.ends_with(s)))
        .count();
    if count >= 2 {
        vec![Issue::from_check(
            check,
            format!("module defines {count} service-style classes (Service/Manager/Handler)"),
            ctx.file_path(),
            1,
            1,
        )]
    } else {
        Vec::new()
    }
}

fn detect_unnecessary_else_after_return(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::If(i) = stmt {
            if !i.orelse.is_empty() && block_ends_with_return(&i.body) {
                let (line, col) = line_col(&ctx.parsed.source, i.start().into());
                issues.push(Issue::from_check(
                    check,
                    "if branch returns but is followed by else; else may be unnecessary",
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_identity_passthrough(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        let (args, body, start, name) = match stmt {
            Stmt::FunctionDef(f) => (&f.args, f.body.as_slice(), f.start(), &f.name),
            Stmt::AsyncFunctionDef(f) => (&f.args, f.body.as_slice(), f.start(), &f.name),
            _ => return,
        };
        let param = single_positional_arg(args);
        let Some(param) = param else { return };
        let Some(Stmt::Return(r)) = last_meaningful_stmt(body) else { return };
        let Some(Expr::Name(n)) = r.value.as_deref() else { return };
        if n.id.as_str() != param {
            return;
        }
        if body.iter().filter(|s| !matches!(s, Stmt::Pass(_))).count() != 1 {
            return;
        }
        let (line, col) = line_col(&ctx.parsed.source, start.into());
        issues.push(Issue::from_check(
            check,
            format!("function `{name}` only returns its single argument"),
            ctx.file_path(),
            line,
            col,
        ));
    });
    issues
}

fn detect_identity_map(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_exprs_in_module(ctx.parsed, &mut |expr| {
        if let Expr::Call(c) = expr {
            if !is_map_call(&c.func) {
                return;
            }
            if c.args.first().is_some_and(is_identity_lambda) {
                let (line, col) = line_col(&ctx.parsed.source, expr.start().into());
                issues.push(Issue::from_check(
                    check,
                    "map(lambda x: x, ...) is an identity; use list(...) or copy directly",
                    ctx.file_path(),
                    line,
                    col,
                ));
            }
        }
    });
    issues
}

fn detect_blanket_except_exception(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_for_try(ctx.parsed, &mut |handler| {
        let ExceptHandler::ExceptHandler(h) = handler;
        if matches!(
            h.type_.as_deref(),
            Some(Expr::Name(n)) if n.id.as_str() == "Exception"
        ) {
            let (line, col) = line_col(&ctx.parsed.source, h.start().into());
            issues.push(Issue::from_check(
                check,
                "except Exception catches nearly all errors; prefer specific exceptions",
                ctx.file_path(),
                line,
                col,
            ));
        }
    });
    issues
}

fn detect_silent_fallback_return_none(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    walk_stmts_for_try(ctx.parsed, &mut |handler| {
        let ExceptHandler::ExceptHandler(h) = handler;
        if handler_returns_none_only(&h.body) {
            let (line, col) = line_col(&ctx.parsed.source, h.start().into());
            issues.push(Issue::from_check(
                check,
                "except handler returns None without logging or re-raising",
                ctx.file_path(),
                line,
                col,
            ));
        }
    });
    issues
}

fn detect_generic_exception_message(check: &dyn Check, ctx: &CheckContext) -> Vec<Issue> {
    let generic = ["error", "failed", "something went wrong", "an error occurred"];
    let mut issues = Vec::new();
    walk_stmts_in_module(ctx.parsed, &mut |stmt| {
        if let Stmt::Raise(r) = stmt {
            if let Some(Expr::Call(c)) = r.exc.as_deref() {
                if is_exception_call(&c.func) {
                    if let Some(msg) = first_string_arg(&c.args) {
                        if generic.iter().any(|g| msg.eq_ignore_ascii_case(g)) {
                            let (line, col) = line_col(&ctx.parsed.source, r.start().into());
                            issues.push(Issue::from_check(
                                check,
                                format!("generic exception message `{msg}`"),
                                ctx.file_path(),
                                line,
                                col,
                            ));
                        }
                    }
                }
            }
        }
    });
    issues
}

fn single_positional_arg(args: &rustpython_ast::Arguments) -> Option<&str> {
    if args.posonlyargs.len() + args.args.len() != 1 {
        return None;
    }
    args.posonlyargs
        .first()
        .map(|a| a.def.arg.as_str())
        .or_else(|| args.args.first().map(|a| a.def.arg.as_str()))
}

fn is_map_call(func: &Expr) -> bool {
    matches!(func, Expr::Name(n) if n.id.as_str() == "map")
}

fn is_identity_lambda(expr: &Expr) -> bool {
    if let Expr::Lambda(l) = expr {
        if l.args.args.len() != 1 {
            return false;
        }
        let param = l.args.args[0].def.arg.as_str();
        return matches!(
            l.body.as_ref(),
            Expr::Name(n) if n.id.as_str() == param
        );
    }
    false
}

fn handler_returns_none_only(body: &[Stmt]) -> bool {
    match last_meaningful_stmt(body) {
        Some(Stmt::Return(r)) => match r.value.as_deref() {
            None => true,
            Some(v) => is_none_constant(v),
        },
        _ => false,
    }
}

fn is_none_constant(expr: &Expr) -> bool {
    matches!(expr, Expr::Constant(c) if matches!(c.value, Constant::None))
}

fn is_exception_call(func: &Expr) -> bool {
    matches!(func, Expr::Name(n) if n.id.as_str() == "Exception")
}

fn first_string_arg(args: &[Expr]) -> Option<String> {
    args.first().and_then(|e| {
        if let Expr::Constant(c) = e {
            if let Constant::Str(s) = &c.value {
                return Some(s.to_string());
            }
        }
        None
    })
}

fn block_ends_with_return(stmts: &[Stmt]) -> bool {
    matches!(last_meaningful_stmt(stmts), Some(Stmt::Return(_)))
}

fn last_meaningful_stmt(stmts: &[Stmt]) -> Option<&Stmt> {
    stmts.iter().rev().find(|s| !matches!(s, Stmt::Pass(_)))
}

fn has_dataclass_decorator(class: &rustpython_ast::StmtClassDef) -> bool {
    class.decorator_list.iter().any(|d| {
        matches!(
            d,
            Expr::Name(n) if n.id.as_str() == "dataclass"
                || matches!(d, Expr::Attribute(a) if a.attr.as_str() == "dataclass")
        )
    })
}

fn is_only_pass_stmts(stmts: &[Stmt]) -> bool {
    !stmts.is_empty() && stmts.iter().all(|s| matches!(s, Stmt::Pass(_)))
}

fn is_constant_bool(expr: &Expr, value: bool) -> bool {
    matches!(
        expr,
        Expr::Constant(c) if matches!(c.value, Constant::Bool(b) if b == value)
    )
}

fn compare_uses_bool_constant(expr: &Expr, value: bool) -> bool {
    matches!(
        expr,
        Expr::Constant(c) if matches!(c.value, Constant::Bool(b) if b == value)
    )
}
